/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_animales;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia Burgos
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form vista1
     */
    public Vista1() {
        initComponents();
        animales = new ArrayList();
        modelo = (DefaultTableModel) this.jTable1_tabla.getModel();
        animal_modificar = new Animal();
        modif = false;
        this.rellenar_array();
        this.rellenar_tabla();
        this.desactivar_botones_gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_titulo = new javax.swing.JLabel();
        jButton1_añadir = new javax.swing.JButton();
        jButton2_modificar = new javax.swing.JButton();
        jButton3_borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabla = new javax.swing.JTable();
        jLabel2_nombre = new javax.swing.JLabel();
        jLabel3_edad = new javax.swing.JLabel();
        jLabel4_provincia = new javax.swing.JLabel();
        jLabel5_familia = new javax.swing.JLabel();
        jTextField1_nombre = new javax.swing.JTextField();
        jTextField2_edad = new javax.swing.JTextField();
        jTextField3_provincia = new javax.swing.JTextField();
        jTextField4_familia = new javax.swing.JTextField();
        jButton4_guardar = new javax.swing.JButton();
        jButton5_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANIMALES");

        jLabel1_titulo.setText("Lista de Animales");

        jButton1_añadir.setText("Añadir");
        jButton1_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_añadirActionPerformed(evt);
            }
        });

        jButton2_modificar.setText("Modificar");
        jButton2_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_modificarActionPerformed(evt);
            }
        });

        jButton3_borrar.setText("Borrar");
        jButton3_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_borrarActionPerformed(evt);
            }
        });

        jTable1_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Provincia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabla);

        jLabel2_nombre.setText("Nombre:");

        jLabel3_edad.setText("Edad:");

        jLabel4_provincia.setText("Provincia:");

        jLabel5_familia.setText("Familia:");

        jTextField1_nombre.setEditable(false);
        jTextField1_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_nombreActionPerformed(evt);
            }
        });

        jTextField2_edad.setEditable(false);

        jTextField3_provincia.setEditable(false);

        jTextField4_familia.setEditable(false);

        jButton4_guardar.setText("Guardar");
        jButton4_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_guardarActionPerformed(evt);
            }
        });

        jButton5_cancelar.setText("Cancelar");
        jButton5_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_titulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2_nombre)
                                    .addComponent(jLabel3_edad)
                                    .addComponent(jLabel4_provincia)
                                    .addComponent(jLabel5_familia))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                                    .addComponent(jTextField2_edad)
                                    .addComponent(jTextField3_provincia)
                                    .addComponent(jTextField4_familia)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1_añadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1_añadir)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3_borrar)
                        .addGap(16, 16, 16)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_nombre)
                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_edad)
                            .addComponent(jTextField2_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4_provincia)
                            .addComponent(jTextField3_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5_familia)
                            .addComponent(jTextField4_familia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5_cancelar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_cancelarActionPerformed
        if(modif==true){
            Animal nuevo = new Animal();
            nuevo.setAnios(animal_modificar.getAnios());
            nuevo.setNombre(animal_modificar.getNombre());
            nuevo.setProvincia(animal_modificar.getProvincia());
            nuevo.setFamilia(animal_modificar.isFamilia());
            
            animales.add(nuevo);
            modelo.addRow(new Object[]{animales.get(this.animales.size()-1).getNombre(),animales.get(this.animales.size()-1).getProvincia()});
        
            this.vaciar_animal_modificar();         
            modelo.fireTableDataChanged();
        }
        this.modif=false;
        this.vaciar_campos_detallados();
        this.editable_no();
        this.desactivar_botones_gc();
        this.activar_botones_amb();
    }//GEN-LAST:event_jButton5_cancelarActionPerformed

    private void jTextField1_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nombreActionPerformed

    private void jButton1_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_añadirActionPerformed
        this.editable_si();
        this.vaciar_campos_detallados();
        this.desactivar_botones_amb();
        this.activar_botones_gc();
        this.jTextField1_nombre.requestFocus();
    }//GEN-LAST:event_jButton1_añadirActionPerformed

    private void jButton4_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_guardarActionPerformed
        Animal nuevo_a = new Animal();
        nuevo_a.setNombre(this.jTextField1_nombre.getText());
        nuevo_a.setProvincia(this.jTextField3_provincia.getText());
        nuevo_a.setAnios(Integer.valueOf(this.jTextField2_edad.getText()));
        if(this.jTextField4_familia.getText()== "si" && this.jTextField4_familia.getText()== "Si")
            nuevo_a.setFamilia(true);
        else
            nuevo_a.setFamilia(false);
        
        animales.add(nuevo_a);
        modelo.addRow(new Object[]{animales.get(this.animales.size()-1).getNombre(),animales.get(this.animales.size()-1).getProvincia()});
        
        this.vaciar_campos_detallados();
        this.vaciar_animal_modificar();
        this.editable_no();        
        this.modif=false;
        this.desactivar_botones_gc();
        this.activar_botones_amb();
    }//GEN-LAST:event_jButton4_guardarActionPerformed

    private void jButton2_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_modificarActionPerformed
        int row = 0;
        row = this.jTable1_tabla.getSelectedRow();
                
        this.modif=true;
        
        this.editable_si();
        this.rellenar_campos_detallados();
        this.rellenar_animal_modificar();
                
        modelo.removeRow(row);
        this.animales.remove(row);
        modelo.fireTableDataChanged();
        this.activar_botones_gc();
        this.desactivar_botones_amb();
    }//GEN-LAST:event_jButton2_modificarActionPerformed

    private void jButton3_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_borrarActionPerformed
        int row = 0;
        row = this.jTable1_tabla.getSelectedRow();
        modelo.removeRow(row);
        this.animales.remove(row);
        modelo.fireTableDataChanged();
        this.vaciar_campos_detallados();
    }//GEN-LAST:event_jButton3_borrarActionPerformed

    private void jTable1_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tablaMouseClicked
        this.rellenar_campos_detallados();
    }//GEN-LAST:event_jTable1_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
            }
        });
        
    }
    
    public void rellenar_array(){
        Animal perro1 = new Animal("Coco", 5, "Granada", true);
        Animal gato1 = new Animal("Misy", 2, "Jaen", false);
        Animal leon1 = new Animal("Simba", 3, "Ciudad del Cabo", false);
        Animal perro2 = new Animal("Cuqui", 5, "Málaga", false);
        Animal tigre1 = new Animal("Tiger", 10, "Nairobi", false);
        
        animales.add(perro1);
        animales.add(gato1);
        animales.add(leon1);
        animales.add(perro2);
        animales.add(tigre1);
    }
    
    public void rellenar_tabla () {
        for (int i = 0; i<animales.size(); i++){
            modelo.addRow(new Object[]{animales.get(i).getNombre(),animales.get(i).getProvincia()});
        }
    }
    
    public void editable_si(){
        this.jTextField1_nombre.setEditable(true);
        this.jTextField2_edad.setEditable(true);
        this.jTextField3_provincia.setEditable(true);
        this.jTextField4_familia.setEditable(true);
    }
    
    public void editable_no() {
        this.jTextField1_nombre.setEditable(false);
        this.jTextField2_edad.setEditable(false);
        this.jTextField3_provincia.setEditable(false);
        this.jTextField4_familia.setEditable(false);
    }
    
    public void vaciar_campos_detallados() {
        this.jTextField1_nombre.setText("");
        this.jTextField2_edad.setText("");
        this.jTextField3_provincia.setText("");
        this.jTextField4_familia.setText("");
    }
    
    public void rellenar_campos_detallados(){
        int row = 0;
        row = this.jTable1_tabla.getSelectedRow();
        String family = "si";
        
        this.jTextField1_nombre.setText(animales.get(row).getNombre()); 
        this.jTextField2_edad.setText(String.valueOf(animales.get(row).getAnios()));
        this.jTextField3_provincia.setText(animales.get(row).getProvincia());
        if (animales.get(row).isFamilia()!=true){
            family = "no";
        }
        this.jTextField4_familia.setText(family);
    }
    
    public void vaciar_animal_modificar() {
        this.animal_modificar.setAnios(0);
        this.animal_modificar.setFamilia(false);
        this.animal_modificar.setNombre("");
        this.animal_modificar.setProvincia("");
    }
    
    public void rellenar_animal_modificar(){
        int row = 0;
        row = this.jTable1_tabla.getSelectedRow();
        
        this.animal_modificar.setNombre(animales.get(row).getNombre());
        this.animal_modificar.setProvincia(animales.get(row).getProvincia());
        this.animal_modificar.setAnios(animales.get(row).getAnios());
        this.animal_modificar.setFamilia(animales.get(row).isFamilia());
    }
    
    public void desactivar_botones_amb(){
        this.jButton1_añadir.setEnabled(false);
        this.jButton2_modificar.setEnabled(false);
        this.jButton3_borrar.setEnabled(false);
        this.jTable1_tabla.setEnabled(false);
    }
    
    public void activar_botones_amb() {
        this.jButton1_añadir.setEnabled(true);
        this.jButton2_modificar.setEnabled(true);
        this.jButton3_borrar.setEnabled(true);
        this.jTable1_tabla.setEnabled(true);
    }
    
    public void desactivar_botones_gc(){
        this.jButton4_guardar.setEnabled(false);
        this.jButton5_cancelar.setEnabled(false);
    }
    
    public void activar_botones_gc() {
        this.jButton4_guardar.setEnabled(true);
        this.jButton5_cancelar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_añadir;
    private javax.swing.JButton jButton2_modificar;
    private javax.swing.JButton jButton3_borrar;
    private javax.swing.JButton jButton4_guardar;
    private javax.swing.JButton jButton5_cancelar;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel2_nombre;
    private javax.swing.JLabel jLabel3_edad;
    private javax.swing.JLabel jLabel4_provincia;
    private javax.swing.JLabel jLabel5_familia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabla;
    private javax.swing.JTextField jTextField1_nombre;
    private javax.swing.JTextField jTextField2_edad;
    private javax.swing.JTextField jTextField3_provincia;
    private javax.swing.JTextField jTextField4_familia;
    // End of variables declaration//GEN-END:variables
    private ArrayList <Animal> animales;
    private DefaultTableModel modelo;
    private Animal animal_modificar;
    private Boolean modif;
}
